version: 2
project_name: dns300

builds:
  - id: default-build
    main: ./cmd/dns300/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: dns300


  - id: mips-build
    main: ./cmd/dns300/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - mips
      - mipsle
    gomips:
      - hardfloat
      - softfloat
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: dns300

dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"


archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']


checksum:
  name_template: 'checksums.txt'
